import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar_AR': {
      "appName":"Claimizer",
      "Claims": "الصيانة",
      "Units" : "الوحدات",
      "statisticsForYourClaims":"إحصائيات طلبات الصيانة",
      'sessionExpired': "انتهت صلاحية الدخول",
      "allClaims":"طلبات الصيانة",
      "newClaims":"طلبات الصيانة الجديدة",
      "assignedClaims":"طلبات الصيانة لدى الفنيين",
      "startedClaims":"طلبات الصيانة تحت الإجراء",
      "completedClaims":"طلبات الصيانة المكتملة",
      "cancelledClaims":"طلبات الصيانة الملغاة",
      "closedClaims":"طلبات الصيانة المغلقة",
      "login":"تسجيل الدخول",
      "welcomePhase":"أهلا بك في إحصائيات الملاك",
      "email":"البريد الالكتروني",
      "password":"كلمة المرور",
      'forgotPassword':"نسيت كلمة المرور؟",
      "somethingWentWrong":"حدث خطأ ما",
      "pleaseTryAgain":"من فضلك اعد المحاولة",
      "reloadScreen":"اعادة التحميل",
      "company":"اسم الشركة",
      "statisticDate":"تاريخ الإحصائية",
      "companies":"الشركات",
      "buildingName":"اسم المبني",
      "error":"خطأ",
      "search":"بحث",
      "logOutPhase":"هل انت متاكد من تسجيل خروجك؟",
      "connectionError":"خطأ في الاتصال",
      "companyData":"بيانات الشركة",
      "sortBy":"ترتيب حسب",
      "name":"الاسم",
      "value":"القيمة",
      "yes":"نعم",
      "no":"لا",
      "chartWidgetPhase":"الرسوم البيانية للإحصاء",
      "landlordStatistics":"إحصائيات الملاك",
      "count":"العدد",
      "userAccounts":"ادارة الحسابات",
      "logout":"تسجيل خروج",
      "changeLanguage":"تغير اللغة",
      "welcome":"اهلا",
      "signedInPhase":"ان الان مسجل الدخول ك ",
      "invalidCredentials":"بيانات غير صحيحة",
      "ok":"موافق",
      "noData":"لا يوجد بيانات",
      "deleteAccountPhase":"هل انت متأكد من حذف هذا الحساب؟",
      "deletedAccountSuccessfully":"تم حذف الحساب بنجاح",
      "emptyEmail":"من فضلك ادخل البريد الالكتروني",
      "emptyPassword":"من فضلك ادخل كلمه المرور",
      "updatePhase":"هناك نسخة جديدة متاحة من التطبيق، يرجى تحديث التطبيق للاستمتاع بالميزات الجديدة",
      "update":"تحديث",
      "signIn":"تسجيل الدخول",
      "hi":"أهلا",
      "language":"اللغة",
      "manageAccounts":"إدارة الحسابات",
      "addAnotherMail":"إضافة حساب أخر",
      "closeAppPhase":"تسجيل الخروج",
      "deleteAccount":"حذف الحساب",
      "from":"من",
      'pleaseSignInAgain': "من فضلك سجل الدخول مجددا",
      "beFalconSolutions":"بي فالكون سوليوشنز",
      "noReportPerm" : "لا يمكنك عرض هذا المحتوى. يرجى ترقية خطة حسابك",
      "statistics" : "الإحصائيات",
      "charts" : "المُخَطَّطات",
      "reports" : "التقارير",
      "priority":"أولوية",
      "createdDate":"تاريخ الانشاء",
      "availableTime": "الوقت المتاح",
      "Version": " رقم الأصدار:",
      "building" : "المبنى",
      "propertyNumber" : "رقم الوحدة",
      "propertyName" : "أسم الوحدة",
      "status" : "الحالة",
      "propertyType" : "نوع الوحدة",
      "usage" : "الأستخدام",
      "category" : "الفئة",
      "view" : "المنظر",
      "position" : "الموقع",
      "model" : "Model",
      "lease" : "إيجار",
      "city" : "المدينة",
      "area" : "المنطقة",
      "plotNo" : "رقم البلوت",
      "owner" : "المالك",
      "ownerNationality" : "الجنسية",
      "contractNo" : "رقم العقد",
      "contractStatus" : "حالة العقد",
      "contractCase" : "النوع",
      "clientName" : "المستأجر",
      "clientNationality" : "الجنسية",
      "clientEmail" : "البريد الإلكتروني",
      "clientMobile" : "رقم الموبيل",
      "netRent" : "عدد الأيام",
      "securityAmount" : "قيمة التأمين",
      "totalRent" : "إجمالي الإيجار",
      "export" : "تصدير",
      "exportPdf" : "تصدير إلي Pdf",
      "exportExcel" : "تصدير إلي Excel",
      "filterBy" : "تصفية حسب",
      "startDate": "تاريخ البدء",
      "endDate": "تاريخ الانتهاء",
      "complete": "مكتمل",
      "low": "منخفض",
      "addAttendance":"أضافة حضور",
      "myAttendance":"حضوري",
      "high": "مرتفع",
      "normal": "عادي",
      "urgent": "عاجل",
      "date" : "التاريخ",
      "showResult" : "عرض النتيجة",
      "new":"جديد",
      "assigned":"تم اختيار فني",
      "closed":"مغلق",
      "started":"بدأت",
      "cancelled":"ملغي",
      "New":"جديد",
      "Assigned":"تم اختيار فني",
      "Closed":"مغلق",
      "Started":"بدأت",
      "Cancelled":"ملغي",
      "Complete": "مكتمل",
      "medium":"متوسط",
      "fileDownloaded" : "تم تحميل الملف"
    },
    'en_US': {
      "fileDownloaded" : "File Downloaded",
      "medium":"Medium",
      "showResult" : "Show Result",
      "date" : "Date",
      "startDate":"Start Date",
      "endDate":"End Date",
      "new":"New",
      "complete":"Completed",
      "assigned":"Assigned",
      "closed":"Closed",
      "started":"Started",
      "cancelled":"Cancelled",
      "New":"New",
      "Complete":"Completed",
      "Assigned":"Assigned",
      "Closed":"Closed",
      "Started":"Started",
      "Cancelled":"Cancelled",
      "low":"Low",
      "high":"High",
      "normal":"Normal",
      "urgent":"Urgent",
      "filterBy" : "Filter By",
      "export" : "Export",
      "exportPdf" : "Export To Pdf",
      "exportExcel" : "Export To Excel",
      "building" : "Building",
      "propertyNumber" : "Property Number",
      "propertyName" : "Property Name",
      "status" : "Status",
      "propertyType" : "Property Type",
      "usage" : "Usage",
      "category" : "Category",
      "view" : "View",
      "position" : "Position",
      "model" : "Model",
      "lease" : "Lease ?",
      "city" : "City",
      "area" : "Area",
      "plotNo" : "Plot No",
      "owner" : "Owner",
      "ownerNationality" : "Nationality",
      "contractNo" : "Contract No",
      "contractStatus" : "Contract Status",
      "contractCase" : "Case",
      "clientName" : "Client Name",
      "clientNationality" : "Client Nationality",
      "clientEmail" : "Client Email",
      "clientMobile" : "Client Mobile",
      "netRent" : "Net Rent",
      "securityAmount" : "Security Amount",
      "totalRent" : "Total Rent",
      "Version": "Version: ",
      "availableTime":"Available Time",
      "createdDate":"Created At",
      "priority":"Priority",
      "Claims" : "Claims",
      "Units" : "Units",
      "statistics" : "Statistics",
      "allClaims":"All Claims",
      "newClaims":"New Claims",
      "assignedClaims":"Assigned Claims",
      "startedClaims":"Started Claims",
      "completedClaims":"Completed Claims",
      "cancelledClaims":"Cancelled Claims",
      "closedClaims":"Closed Claims",
      "charts" : "Charts",
      "reports" : "Reports",
      "statisticsForYourClaims":"Claims Dashboard",
  "noReportPerm" : "You cannot view this content. Please upgrade your account plan.",
      'sessionExpired': "Session Expired",
      'pleaseSignInAgain': "Please SignIn Again",
      "appName":"Claimizer",
      "login":"Login",
      "welcomePhase":"Welcome To Landlord Statistics",
      "email":"Email",
      "password":"Password",
      'forgotPassword':"Forgot password?",
      "somethingWentWrong":"Something Went Wrong",
      "pleaseTryAgain":"Please Try Again",
      "reloadScreen":"Reload Screen",
      "company":"Company",
      "statisticDate":"Statistic Date",
      "companies":"Companies",
      "buildingName":"Building",
      "error":"Error",
      "search":"Search",
      "logOutPhase":"Are you sure you want to logout ?",
      "connectionError":"Connection Error",
      "companyData":"Company Data",
      "sortBy":"Sort By",
      "name":"Name",
      "value":"Value",
      "yes":"Yes",
      "no":"No",
      "chartWidgetPhase":"Charts For Statistics",
      "landlordStatistics":"Landlord Statistics",
      "count":"Count",
      "userAccounts":"User Accounts",
      "logout":"Logout",
      "changeLanguage":"Change Language",
      "welcome":"Welcome",
      "signedInPhase":"You are now signed in as",
      "ok":"OK",
      "noData":"There is no data",
      "deleteAccountPhase":"Are you sure you want to delete this account?",
      "deletedAccountSuccessfully":"Account has been deleted successfully",
      "emptyEmail":"Please enter your email",
      "emptyPassword":"Please enter your password",
      "updatePhase":"There is a new version of application available , please update the application to enjoy new features",
      "update":"Update",
      "landLordStatistics":"Landlord Statistics",
      "signIn":"Sign In",
      "hi":"Hi",
      "language":"Language",
      "manageAccounts":"Manage Accounts",
      "addAnotherMail":"Add Another Accounts",
      "closeAppPhase":"Logout",
      "deleteAccount":"Delete Account",
      "from":"From",
      "beFalconSolutions":"Be Falcon Solutions"
    },
  };
}